kafka:
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  security:
    protocol: PLAINTEXT

  producer:
    key:
      serializer: org.apache.kafka.common.serialization.StringSerializer
    value:
      serializer: org.apache.kafka.common.serialization.StringSerializer
    acks: all
    retries: 3
    batch:
      size: 16384
    linger:
      ms: 1
    buffer:
      memory: 33554432
    enable:
      idempotence: true

quarkus:
  http:
    port: 8082
    cors: true
  kafka:
    devservices:
      enabled: false
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5433/keycloak_events

  hibernate-orm:
    database:
      generation: update
    log:
      sql: true

  # Health Check Configuration
  health:
    enabled: true
    extensions:
      enabled: true
    readiness:
      enabled: true
      path: /health/ready
    liveness:
      enabled: true
      path: /health/live
  smallrye-health:
    ui:
      enable: true
      path: /health-ui

  # Metrics Configuration
  micrometer:
    export:
      prometheus:
        enabled: true
        path: /q/metrics

  # Logging Configuration
  log:
    level: INFO
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
      color: true
