apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-events-connector
  namespace: keycloak-events
data:
  connector.json: |
    {
      "name": "keycloak-events-sink",
      "config": {
        "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
        "tasks.max": "1",
        "topics": "keycloak-events",
        "connection.url": "jdbc:postgresql://postgres:5432/keycloak_events",
        "connection.user": "postgres",
        "connection.password": "postgres",
        "auto.create": "true",
        "auto.evolve": "true",
        "insert.mode": "upsert",
        "pk.mode": "record_key",
        "pk.fields": "id",
        "table.name.format": "keycloak_events",
        "transforms": "unwrap",
        "transforms.unwrap.type": "io.debezium.transforms.ExtractNewRecordState",
        "transforms.unwrap.drop.tombstones": "false",
        "transforms.unwrap.delete.handling.mode": "none"
      }
    } 