apiVersion: v1
kind: ConfigMap
metadata:
  name: smartface-config
  namespace: smartface
data:
  KC_EVENTS_LISTENER_DB_PASSWORD: password
  KC_EVENTS_LISTENER_DB_URL: jdbc:postgresql://postgres:5432/keycloak
  KC_EVENTS_LISTENER_DB_USER: keycloak
  KC_EVENTS_LISTENER_KAFKA_BOOTSTRAP_SERVERS: redpanda:29092
  KC_EVENTS_LISTENER_KAFKA_CLIENT_ID: keycloak-event-listener
  KC_EVENTS_LISTENER_KAFKA_TOPIC: keycloak_events
  QUARKUS_GRPC_SERVER_PORT: "9000"
  QUARKUS_HTTP_PORT: "8080"
  QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/keycloak
  QUARKUS_DATASOURCE_USERNAME: keycloak
  QUARKUS_DATASOURCE_PASSWORD: password 