apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smartface

resources:
  - ../../base

patches:
  - path: event-service-patch.yaml
  - path: keycloak-patch.yaml

configMapGenerator:
  - name: smartface-config
    behavior: merge
    envs:
      - dev.env 